# Generated by Django 5.2.11 on 2026-05-09 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_filaprato_status_alter_pedido_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="ready_printed_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
