# Generated by Django 6.0.5 on 2026-05-26 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_filaprato_status_alter_pedido_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="senha_numero",
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
