# Generated by Django 5.2.11 on 2026-05-28 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_pedido_senha_numero"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="caixa",
            field=models.CharField(
                blank=True,
                help_text="Identificador digitado no terminal (Ex: Caixa 01)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="pedido",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name="pedido",
            index=models.Index(
                fields=["status", "updated_at"], name="core_pedido_status_9c3cd3_idx"
            ),
        ),
    ]
