# Generated by Django 6.0.4 on 2026-06-26 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_pedido_caixa_pedido_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prato',
            name='nome_pagina',
            field=models.CharField(blank=True, help_text='Nome alternativo para exibição na página de produção', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('PRODUCAO', 'Producao'), ('FINALIZADO', 'Finalizado'), ('RECHAMADO', 'Rechamado'), ('RETIRADO', 'Retirado'), ('CANCELADO', 'Cancelado')], db_index=True, default='PENDENTE', max_length=20),
        ),
    ]
